"""
Train a linear probe to predict verbalised confidence from embeddings.

This script loads pickle files generated by process_generations_for_linear_probe.py,
extracts layer 33 embeddings from emb_tok_bef_gen, and trains a regressor to predict
verbalised_confidence (0-1).

Usage:
    python train_verbalised_confidence_probe.py \
        --train_path semantic_uncertainty/out/1/train_linear_probe.pkl \
        --val_path semantic_uncertainty/out/1/validation_linear_probe.pkl \
        [--output_dir ./results] \
        [--model_type ridge] \
        [--alpha 1.0] \
        [--plot]
"""

import argparse
import pickle
from datetime import datetime
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


def load_verbalised_confidence_data(train_path, val_path, layer_idx=32):
    """
    Load pickle files and extract verbalised confidence and embeddings.
    
    Args:
        train_path: Path to train_linear_probe.pkl
        val_path: Path to validation_linear_probe.pkl
        layer_idx: Index of layer to extract (default: 33, last layer)
    
    Returns:
        X_train, y_train, X_val, y_val as numpy arrays
    """
    # Load training data
    with open(train_path, 'rb') as f:
        train_data = pickle.load(f)
    
    # Load validation data
    with open(val_path, 'rb') as f:
        val_data = pickle.load(f)
    
    def extract_features_and_labels(data_dict):
        """Extract embeddings (layer 33) and verbalised confidence from data dict."""
        X_list = []
        y_list = []
        
        for example_id, example_data in data_dict.items():
            responses = example_data.get('responses', [])
            # Each example should have one response (as per user's note)
            if len(responses) == 0:
                print(f"ERROR: No responses for example {example_id}")
                continue
            
            if len(responses) > 1:
                print(f"ERROR: Multiple responses for example {example_id}")

            response = responses[0]  # Take the first (and only) response
            verbalised_confidence = response.get('verbalised_confidence')
            # TODO: make this more general (take in the option to choose which token)
            emb_tok_bef_gen = response.get('emb_tok_bef_gen')
            
            if verbalised_confidence is None or emb_tok_bef_gen is None:
                print(f'ERROR: No verbalised confidence or embeddings for example {example_id}')
                continue
            
            # TODO: make this less verbose
            # Convert to numpy if needed
            if isinstance(emb_tok_bef_gen, np.ndarray):
                emb_array = emb_tok_bef_gen
            elif hasattr(emb_tok_bef_gen, 'numpy'):
                emb_array = emb_tok_bef_gen.numpy()
            elif hasattr(emb_tok_bef_gen, 'cpu'):
                emb_array = emb_tok_bef_gen.cpu().numpy()
            else:
                emb_array = np.array(emb_tok_bef_gen)
            

            # Extract layer 33 (last layer, index -1 or 33)
            # emb_tok_bef_gen shape: [num_layers, batch_size, hidden_dim]
            # layer_emb shape: [num_layers, batch_size, hidden_dim]
            # Prints just to confirm
            layer_emb = emb_array[layer_idx]
            layer_emb = layer_emb[0]
            
            # Flatten to 1D if needed
            layer_emb = layer_emb.flatten()

            X_list.append(layer_emb)
            y_list.append(float(verbalised_confidence))
        
        return np.array(X_list), np.array(y_list)
    
    # np arrays: x_train/val shape = (num_examples, feature_dim)
    # y_train/val shape = (num_examples) -> floats (verbalised confidence)
    X_train, y_train = extract_features_and_labels(train_data)
    X_val, y_val = extract_features_and_labels(val_data)
    
    print(f"Loaded {len(X_train)} training examples, {len(X_val)} validation examples")
    print(f"Embedding dimension: {X_train.shape[1]}")
    print(f"Confidence range: [{y_train.min():.3f}, {y_train.max():.3f}]")
    
    return X_train, y_train, X_val, y_val


def train_verbalised_confidence_probe(X_train, y_train, X_val, y_val, 
                                       model_type='ridge', alpha=1.0):
    """
    Train a regressor to predict verbalised confidence.
    
    Args:
        X_train: Training embeddings (n_samples, n_features)
        y_train: Training confidence values (n_samples,)
        X_val: Validation embeddings (n_samples, n_features)
        y_val: Validation confidence values (n_samples,)
        model_type: 'ridge' or 'linear'.
        alpha: Regularization strength for Ridge (how much to penalise large weights) (ignored for linear).
    
    Returns:
        Trained model and metrics dictionary
    """
    # Initialize model
    if model_type.lower() == 'ridge':
        model = Ridge(alpha=alpha, random_state=42)
    elif model_type.lower() == 'linear':
        model = LinearRegression()
    else:
        raise ValueError(f"Unknown model_type: {model_type}. Use 'ridge' or 'linear'")
    
    # Train model
    print(f"\nTraining {model_type} regressor...")
    model.fit(X_train, y_train)
    
    # Predictions
    y_train_pred = model.predict(X_train)
    y_val_pred = model.predict(X_val)
    
    # Clip predictions to [0, 1] range
    y_train_pred = np.clip(y_train_pred, 0, 1)
    y_val_pred = np.clip(y_val_pred, 0, 1)
    
    # Calculate metrics
    train_mse = mean_squared_error(y_train, y_train_pred)
    train_mae = mean_absolute_error(y_train, y_train_pred) # Mean Absolute Error
    train_r2 = r2_score(y_train, y_train_pred) # R-squared score
    
    val_mse = mean_squared_error(y_val, y_val_pred)
    val_mae = mean_absolute_error(y_val, y_val_pred)
    val_r2 = r2_score(y_val, y_val_pred)
    
    metrics = {
        'train': {
            'mse': train_mse,
            'mae': train_mae,
            'r2': train_r2,
        },
        'val': {
            'mse': val_mse,
            'mae': val_mae,
            'r2': val_r2,
        }
    }
    
    # Print metrics
    print("\nTraining Metrics:")
    print(f"  MSE:  {train_mse:.6f}")
    print(f"  MAE:  {train_mae:.6f}")
    print(f"  R²:   {train_r2:.6f}")
    
    print("\nValidation Metrics:")
    print(f"  MSE:  {val_mse:.6f}")
    print(f"  MAE:  {val_mae:.6f}")
    print(f"  R²:   {val_r2:.6f}")

    return model, metrics


def _get_run_dir(output_dir: Path, layer_idx: int) -> Path:
    """Return output_dir / layer_{n} / k where k is the first empty subdir 1, 2, 3, ..."""
    layer_dir = output_dir / f"layer_{layer_idx}"
    layer_dir.mkdir(parents=True, exist_ok=True)
    k = 1
    while (layer_dir / str(k)).exists():
        k += 1
    run_dir = layer_dir / str(k)
    run_dir.mkdir(parents=True, exist_ok=True)
    return run_dir


def write_config_txt(run_dir: Path, args, model_type: str, n_train: int, n_val: int,
                     metrics: dict, train_path: str, val_path: str) -> None:
    """Write a config/summary txt file into run_dir."""
    lines = [
        "Verbalised confidence probe – training configuration and results",
        "=" * 60,
        f"Model type: {model_type}",
        f"Layer index: {args.layer_idx}",
        f"Embedding: emb_tok_bef_gen",
        f"Alpha (regularization): {args.alpha}",
        f"Train path: {train_path}",
        f"Val path: {val_path}",
        "",
        "Data",
        "-" * 40,
        f"Number of training samples: {n_train}",
        f"Number of validation samples: {n_val}",
        f"Split (train / val): {n_train} / {n_val}",
        "",
    ]
    lines.extend([
        "Final metrics",
        "-" * 40,
        "Train:",
        f"  MSE:  {metrics['train']['mse']:.6f}",
        f"  MAE:  {metrics['train']['mae']:.6f}",
        f"  R²:   {metrics['train']['r2']:.6f}",
        "Validation:",
        f"  MSE:  {metrics['val']['mse']:.6f}",
        f"  MAE:  {metrics['val']['mae']:.6f}",
        f"  R²:   {metrics['val']['r2']:.6f}",
        "",
        f"Trained at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    ])
    with open(run_dir / 'config.txt', 'w') as f:
        f.write("\n".join(lines))


def plot_results(y_true, y_pred, split_name, output_dir=None):
    """
    Create visualization plots for regression results.
    
    Args:
        y_true: True confidence values
        y_pred: Predicted confidence values
        split_name: Name for the split (train/val)
        output_dir: Directory to save plots (optional)
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    
    # Scatter plot: predicted vs actual
    ax1 = axes[0]
    ax1.scatter(y_true, y_pred, alpha=0.5, s=20)
    ax1.plot([0, 1], [0, 1], 'r--', lw=2, label='Perfect prediction')
    ax1.set_xlabel('True Verbalised Confidence')
    ax1.set_ylabel('Predicted Verbalised Confidence')
    ax1.set_title(f'{split_name.capitalize()}: Predicted vs Actual')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.set_xlim([0, 1])
    ax1.set_ylim([0, 1])
    
    # Residual plot
    ax2 = axes[1]
    residuals = y_true - y_pred
    ax2.scatter(y_pred, residuals, alpha=0.5, s=20)
    ax2.axhline(y=0, color='r', linestyle='--', lw=2)
    ax2.set_xlabel('Predicted Verbalised Confidence')
    ax2.set_ylabel('Residuals (True - Predicted)')
    ax2.set_title(f'{split_name.capitalize()}: Residual Plot')
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        plt.savefig(output_dir / f'{split_name}_regression_plots.png', dpi=150, bbox_inches='tight')
        print(f"\nSaved plots to {output_dir / f'{split_name}_regression_plots.png'}")
    
    plt.show()


def main():
    parser = argparse.ArgumentParser(
        description="Train linear probe to predict verbalised confidence from embeddings"
    )
    parser.add_argument(
        '--train_path',
        type=str,
        required=True,
        help='Path to train_linear_probe.pkl file'
    )
    parser.add_argument(
        '--val_path',
        type=str,
        required=True,
        help='Path to validation_linear_probe.pkl file'
    )
    parser.add_argument(
        '--output_dir',
        type=str,
        default='./results',
        help='Output directory for plots and saved model (default: ./results)'
    )
    parser.add_argument(
        '--model_type',
        type=str,
        default='ridge',
        choices=['ridge', 'linear'],
        help='Type of regression model: ridge or linear (default: ridge)'
    )
    parser.add_argument(
        '--alpha',
        type=float,
        default=1.0,
        help='Regularization strength for Ridge regression (default: 1.0)'
    )
    parser.add_argument(
        '--layer_idx',
        type=int,
        default=32,
        help='Layer index to extract from embeddings (default: 32)'
    )
    parser.add_argument(
        '--plot',
        action='store_true',
        help='Generate and display plots'
    )
    parser.add_argument(
        '--save_model',
        default=True,
        action='store_true',
        help='Save trained model to pickle file'
    )
    
    args = parser.parse_args()
    
    # Load data
    print("Loading data...")
    X_train, y_train, X_val, y_val = load_verbalised_confidence_data(
        args.train_path, 
        args.val_path,
        layer_idx=args.layer_idx
    )
    
    # Train model
    model, metrics = train_verbalised_confidence_probe(
        X_train, y_train, X_val, y_val,
        model_type=args.model_type,
        alpha=args.alpha
    )
    
    # Output directory and run_dir (layer_n/k) for plots and/or model save
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    run_dir = _get_run_dir(output_dir, args.layer_idx) if (args.plot or args.save_model) else None
    
    # Generate plots if requested (save into layer_n folder)
    if args.plot:
        print("\nGenerating plots...")
        plot_results(y_train, model.predict(X_train), 'train', str(run_dir))
        plot_results(y_val, model.predict(X_val), 'val', str(run_dir))
    
    # Save model and artifacts to results/layer_{n}/{k}/
    if args.save_model:
        model_path = run_dir / 'verbalised_confidence_probe.pkl'
        with open(model_path, 'wb') as f:
            pickle.dump({
                'model': model,
                'metrics': metrics,
                'layer_idx': args.layer_idx,
                'model_type': args.model_type,
                'alpha': args.alpha if args.model_type == 'ridge' else None,
            }, f)
        print(f"\nSaved model to {model_path}")
        write_config_txt(
            run_dir, args, args.model_type,
            n_train=len(X_train), n_val=len(X_val),
            metrics=metrics,
            train_path=str(args.train_path), val_path=str(args.val_path),
        )
        print(f"Saved config to {run_dir / 'config.txt'}")


if __name__ == '__main__':
    main()
