"""
Train linear probes for multiple token positions across all layers to predict verbalised confidence.

This script loads pickle files generated by process_generations_verbalised_embeddings.py,
extracts embeddings_guess and embeddings_probability (lists of token embeddings),
trains independent probes for each token position and layer, and saves results under
results/mult_toks_all_layers/<run_id>/tok_n_guess/ and tok_n_prob/ directories.

Usage:
    python train_multitoken_verbalised_confidence_probe.py \
        --train_path semantic_uncertainty/processed_generations/1/train_verbalised_embeddings.pkl \
        --val_path semantic_uncertainty/processed_generations/1/validation_verbalised_embeddings.pkl \
        [--output_dir ./results] \
        [--model_type ridge] \
        [--alpha 1.0] \
        [--plot]
"""

import argparse
import logging
import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

try:
    from verbalised_confidence_probes.train_verbalised_confidence_probe import (
        plot_results,
        train_verbalised_confidence_probe,
        write_config_txt,
    )
except ImportError:
    print("Importing from train_verbalised_confidence_probe.py this way")
    from train_verbalised_confidence_probe import (
        plot_results,
        train_verbalised_confidence_probe,
        write_config_txt,
    )


def _load_pickle_batches_multitoken(path):
    """
    Load a multi-dump pickle file (written as multiple pickle.dump batches) in a loop.
    Extracts verbalised_confidence, embeddings_guess, and embeddings_probability per example.
    """
    data = {}
    with open(path, 'rb') as f:
        while True:
            try:
                batch = pickle.load(f)
            except EOFError:
                break
            if not isinstance(batch, dict):
                logging.warning(f"ERROR: Batch is not a dict: {type(batch)}")
                continue
            for example_id, example_data in batch.items():
                responses = example_data.get('responses', [])
                if not responses:
                    continue
                r = responses[0]  # Use first response
                vc = r.get('verbalised_confidence')
                emb_guess = r.get('embeddings_guess')
                emb_prob = r.get('embeddings_probability')
                if vc is None or emb_guess is None or emb_prob is None:
                    logging.warning(f"ERROR: Missing data for example {example_id}")
                    continue
                data[example_id] = {
                    'responses': [{
                        'verbalised_confidence': vc,
                        'embeddings_guess': emb_guess,
                        'embeddings_probability': emb_prob,
                    }]
                }
    return data


def _tensor_to_numpy(obj):
    """Convert tensor or array-like to numpy."""
    if isinstance(obj, np.ndarray):
        return obj
    if hasattr(obj, 'cpu') and hasattr(obj, 'numpy'):
        return obj.cpu().numpy()
    if hasattr(obj, 'numpy'):
        return obj.numpy()
    return np.asarray(obj)


def load_multitoken_verbalised_confidence_data(train_path, val_path):
    """
    Load pickle files and extract verbalised confidence and embeddings for all token positions.
    
    Returns:
        dict: {
            'guess': {
                token_pos: (X_train, X_val, y_train, y_val, n_layers)
            },
            'probability': {
                token_pos: (X_train, X_val, y_train, y_val, n_layers)
            }
        }
    """
    train_data = _load_pickle_batches_multitoken(train_path)
    val_data = _load_pickle_batches_multitoken(val_path)
    
    def extract_token_positions_and_labels(data_dict, embedding_type):
        """
        Extract embeddings for all token positions from embeddings_guess or embeddings_probability.
        
        Returns:
            dict: {token_pos: (X_array, y_array)} where X_array shape is (n_examples, n_layers, hidden_dim)
        """
        # First pass: determine max token positions and validate consistency
        max_token_pos = -1
        n_layers = None
        hidden_dim = None
        
        for example_id, example_data in data_dict.items():
            responses = example_data.get('responses', [])
            if len(responses) == 0:
                continue
            response = responses[0]
            emb_list = response.get(f'embeddings_{embedding_type}')
            if emb_list is None or len(emb_list) == 0:
                continue
            
            # Check first embedding to get shape info
            # emb_array shape: (num_layers, batch_size, sequence_length, hidden_dim)
            first_emb = _tensor_to_numpy(emb_list[0])
            if n_layers is None:
                n_layers = first_emb.shape[0]
                hidden_dim = first_emb.shape[3] if len(first_emb.shape) >= 4 else (first_emb.shape[2] if len(first_emb.shape) >= 3 else first_emb.shape[1])
            
            max_token_pos = max(max_token_pos, len(emb_list) - 1)
        
        if max_token_pos < 0:
            return {}
        
        # Second pass: extract data for each token position
        token_data = {pos: {'X': [], 'y': []} for pos in range(max_token_pos + 1)}
        
        for example_id, example_data in data_dict.items():
            responses = example_data.get('responses', [])
            if len(responses) == 0:
                continue
            response = responses[0]
            verbalised_confidence = response.get('verbalised_confidence')
            emb_list = response.get(f'embeddings_{embedding_type}')
            
            if verbalised_confidence is None or emb_list is None:
                continue
            
            # Extract embeddings for each token position
            for token_pos, emb in enumerate(emb_list):
                if token_pos > max_token_pos:
                    break
                
                emb_array = _tensor_to_numpy(emb)
                # emb_array shape: (num_layers, batch_size, sequence_length, hidden_dim)
                layer_embs = emb_array[:, 0, -1, :]
                
                # Validate shape
                if layer_embs.shape[0] != n_layers or layer_embs.shape[1] != hidden_dim:
                    logging.warning(f"Shape mismatch for example {example_id}, token {token_pos}: expected ({n_layers}, {hidden_dim}), got {layer_embs.shape}")
                    continue
                
                token_data[token_pos]['X'].append(layer_embs)
                token_data[token_pos]['y'].append(float(verbalised_confidence))
        
        # Convert to numpy arrays
        result = {}
        for token_pos in range(max_token_pos + 1):
            if len(token_data[token_pos]['X']) == 0:
                continue
            X_array = np.array(token_data[token_pos]['X'])
            y_array = np.array(token_data[token_pos]['y'])
            result[token_pos] = (X_array, y_array, n_layers)
        
        return result
    
    # Extract data for both embedding types
    train_guess = extract_token_positions_and_labels(train_data, 'guess')
    train_prob = extract_token_positions_and_labels(train_data, 'probability')
    val_guess = extract_token_positions_and_labels(val_data, 'guess')
    val_prob = extract_token_positions_and_labels(val_data, 'probability')
    
    # Match train and val token positions
    result = {'guess': {}, 'probability': {}}
    
    for embedding_type, train_dict, val_dict in [('guess', train_guess, val_guess), ('probability', train_prob, val_prob)]:
        # Find common token positions
        common_positions = set(train_dict.keys()) & set(val_dict.keys())
        if len(common_positions) == 0:
            logging.warning(f"No common token positions found for {embedding_type} embeddings")
            continue
        
        for token_pos in sorted(common_positions):
            X_train, y_train, n_layers_train = train_dict[token_pos]
            X_val, y_val, n_layers_val = val_dict[token_pos]
            
            if n_layers_train != n_layers_val:
                logging.warning(f"Layer count mismatch for {embedding_type} token {token_pos}: train={n_layers_train}, val={n_layers_val}")
                continue
            
            if len(X_train) == 0 or len(X_val) == 0:
                logging.warning(f"No examples for {embedding_type} token {token_pos}")
                continue
            
            result[embedding_type][token_pos] = (X_train, X_val, y_train, y_val, n_layers_train)
            logging.info(f"Loaded {embedding_type} token {token_pos}: {len(X_train)} train, {len(X_val)} val, {n_layers_train} layers")
    
    return result


def _get_run_base_dir(output_dir: Path) -> Path:
    """Return output_dir / mult_toks_all_layers / k where k is the first unused 1, 2, 3, ..."""
    output_dir.mkdir(parents=True, exist_ok=True)
    mult_toks_dir = output_dir / "mult_toks_all_layers"
    mult_toks_dir.mkdir(parents=True, exist_ok=True)
    k = 1
    while (mult_toks_dir / str(k)).exists():
        k += 1
    run_base = mult_toks_dir / str(k)
    run_base.mkdir(parents=True, exist_ok=True)
    return run_base


def _plot_metrics_by_layer(layer_numbers, train_metrics, val_metrics, metric_name, metric_label, output_dir: Path):
    """Plot one metric (train and val) vs layer number and save to output_dir."""
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(layer_numbers, train_metrics, 'o-', label='Train', markersize=4)
    ax.plot(layer_numbers, val_metrics, 's-', label='Validation', markersize=4)
    ax.set_xlabel('Layer number')
    ax.set_ylabel(metric_label)
    ax.set_title(f'{metric_label} by layer')
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    out_path = output_dir / f'{metric_name}_by_layer.png'
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    logging.info(f"Saved {out_path}")


def _plot_all_metrics_by_layer(output_dir: Path, layer_numbers, train_metrics_list, val_metrics_list):
    """Create 3 graphs: MSE, MAE, R² vs layer number for a single token position."""
    metrics_config = [
        ('mse', 'MSE', train_metrics_list[0], val_metrics_list[0]),
        ('mae', 'MAE', train_metrics_list[1], val_metrics_list[1]),
        ('r2', 'R²', train_metrics_list[2], val_metrics_list[2]),
    ]
    for metric_name, metric_label, train_vals, val_vals in metrics_config:
        _plot_metrics_by_layer(layer_numbers, train_vals, val_vals, metric_name, metric_label, output_dir)


def _plot_metrics_all_tokens(run_base: Path, all_token_metrics):
    """
    Create 6 graphs: 3 for guess tokens (MSE, MAE, R²) and 3 for probability tokens (MSE, MAE, R²).
    Each graph shows all token positions of that type with different colors.
    
    Args:
        run_base: Base directory for saving plots
        all_token_metrics: dict with structure:
            {
                'tok_0_guess': {'train': [mse, mae, r2], 'val': [mse, mae, r2], 'layers': [1,2,...]},
                'tok_1_guess': {...},
                ...
            }
    """
    metrics_config = [
        ('mse', 'MSE', 0),
        ('mae', 'MAE', 1),
        ('r2', 'R²', 2),
    ]
    
    # Separate tokens by type (guess vs probability)
    guess_tokens = {}
    prob_tokens = {}
    for token_name, metrics_dict in all_token_metrics.items():
        if 'guess' in token_name:
            guess_tokens[token_name] = metrics_dict
        elif 'probability' in token_name or 'prob' in token_name:
            prob_tokens[token_name] = metrics_dict
    
    # Create graphs for guess tokens
    if len(guess_tokens) > 0:
        # Get color cycle for guess tokens
        guess_colors = plt.cm.tab10(np.linspace(0, 1, len(guess_tokens)))
        
        for metric_name, metric_label, metric_idx in metrics_config:
            fig, ax = plt.subplots(figsize=(10, 6))
            
            for idx, (token_name, metrics_dict) in enumerate(sorted(guess_tokens.items())):
                layer_numbers = metrics_dict['layers']
                train_vals = metrics_dict['train'][metric_idx]
                val_vals = metrics_dict['val'][metric_idx]
                color = guess_colors[idx]
                
                ax.plot(layer_numbers, train_vals, 'o-', label=f'{token_name} (Train)', 
                       markersize=4, color=color, linestyle='-', alpha=0.7)
                ax.plot(layer_numbers, val_vals, 's--', label=f'{token_name} (Val)', 
                       markersize=4, color=color, linestyle='--', alpha=0.7)
            
            ax.set_xlabel('Layer number')
            ax.set_ylabel(metric_label)
            ax.set_title(f'{metric_label} by layer - Guess tokens')
            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
            ax.grid(True, alpha=0.3)
            fig.tight_layout()
            out_path = run_base / f'{metric_name}_all_tokens_guess.png'
            fig.savefig(out_path, dpi=150, bbox_inches='tight')
            plt.close(fig)
            logging.info(f"Saved {out_path}")
    
    # Create graphs for probability tokens
    if len(prob_tokens) > 0:
        # Get color cycle for probability tokens
        prob_colors = plt.cm.tab10(np.linspace(0, 1, len(prob_tokens)))
        
        for metric_name, metric_label, metric_idx in metrics_config:
            fig, ax = plt.subplots(figsize=(10, 6))
            
            for idx, (token_name, metrics_dict) in enumerate(sorted(prob_tokens.items())):
                layer_numbers = metrics_dict['layers']
                train_vals = metrics_dict['train'][metric_idx]
                val_vals = metrics_dict['val'][metric_idx]
                color = prob_colors[idx]
                
                ax.plot(layer_numbers, train_vals, 'o-', label=f'{token_name} (Train)', 
                       markersize=4, color=color, linestyle='-', alpha=0.7)
                ax.plot(layer_numbers, val_vals, 's--', label=f'{token_name} (Val)', 
                       markersize=4, color=color, linestyle='--', alpha=0.7)
            
            ax.set_xlabel('Layer number')
            ax.set_ylabel(metric_label)
            ax.set_title(f'{metric_label} by layer - Probability tokens')
            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
            ax.grid(True, alpha=0.3)
            fig.tight_layout()
            out_path = run_base / f'{metric_name}_all_tokens_probability.png'
            fig.savefig(out_path, dpi=150, bbox_inches='tight')
            plt.close(fig)
            logging.info(f"Saved {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Train verbalised-confidence probes for multiple token positions across all layers"
    )
    parser.add_argument('--train_path', type=str, required=True, 
                       help='Path to train pickle file (from process_generations_verbalised_embeddings.py)')
    parser.add_argument('--val_path', type=str, required=True, 
                       help='Path to validation pickle file (from process_generations_verbalised_embeddings.py)')
    parser.add_argument(
        '--output_dir',
        type=str,
        default='./results',
        help='Output directory (default: ./results); run dir is output_dir/mult_toks_all_layers/<run_id>/',
    )
    parser.add_argument(
        '--model_type',
        type=str,
        default='ridge',
        choices=['ridge', 'linear'],
        help='Type of regression model (default: ridge)',
    )
    parser.add_argument(
        '--alpha',
        type=float,
        default=1.0,
        help='Regularization strength for Ridge (default: 1.0)',
    )
    parser.add_argument('--plot', default=True, action='store_true', help='Save train/val regression plots per layer')
    parser.add_argument('--save_model', default=True, action='store_true', help='Save trained probes to pickle')
    args = parser.parse_args()
    
    # Set up logging first
    run_base = _get_run_base_dir(Path(args.output_dir))
    output_log_path = run_base / 'output.log'
    
    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s %(levelname)-8s %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S',
        handlers=[
            logging.FileHandler(output_log_path, mode='w'),
            logging.StreamHandler()
        ]
    )
    
    logging.info(f"Run directory: {run_base}")
    logging.info(f"Loading data from {args.train_path} and {args.val_path}")
    
    # Load data
    data_dict = load_multitoken_verbalised_confidence_data(args.train_path, args.val_path)
    
    if len(data_dict['guess']) == 0 and len(data_dict['probability']) == 0:
        logging.error("No valid data loaded. Exiting.")
        return
    
    # Store metrics for cross-token graphs
    all_token_metrics = {}
    
    # Train probes for each embedding type
    for embedding_type in ['guess', 'probability']:
        if embedding_type not in data_dict or len(data_dict[embedding_type]) == 0:
            logging.info(f"No data for {embedding_type} embeddings, skipping...")
            continue
        
        logging.info(f"\n{'='*60}")
        logging.info(f"Processing {embedding_type} embeddings")
        logging.info(f"{'='*60}")
        
        # Train for each token position
        for token_pos in sorted(data_dict[embedding_type].keys()):
            X_train, X_val, y_train, y_val, n_layers = data_dict[embedding_type][token_pos]
            
            token_dir_name = f"tok_{token_pos}_{embedding_type}"
            token_dir = run_base / token_dir_name
            token_dir.mkdir(parents=True, exist_ok=True)
            
            logging.info(f"\nTraining probes for {token_dir_name} ({n_layers} layers)")
            
            layer_numbers = []
            train_mse, train_mae, train_r2 = [], [], []
            val_mse, val_mae, val_r2 = [], [], []
            
            # Train probe for each layer
            for layer_idx in range(n_layers):
                layer_name = f"layer_{layer_idx + 1}"
                layer_dir = token_dir / layer_name
                layer_dir.mkdir(parents=True, exist_ok=True)
                
                # Extract layer embeddings: X_train shape is (n_examples, n_layers, hidden_dim)
                X_train_l = X_train[:, layer_idx, :]
                X_val_l = X_val[:, layer_idx, :]
                
                # Train probe
                model, metrics = train_verbalised_confidence_probe(
                    X_train_l, y_train, X_val_l, y_val,
                    model_type=args.model_type,
                    alpha=args.alpha,
                    verbose=False,
                )
                
                layer_numbers.append(layer_idx + 1)
                train_mse.append(metrics['train']['mse'])
                train_mae.append(metrics['train']['mae'])
                train_r2.append(metrics['train']['r2'])
                val_mse.append(metrics['val']['mse'])
                val_mae.append(metrics['val']['mae'])
                val_r2.append(metrics['val']['r2'])
                
                # Save plots if requested
                if args.plot:
                    plot_results(y_train, model.predict(X_train_l), 'train', str(layer_dir))
                    plot_results(y_val, model.predict(X_val_l), 'val', str(layer_dir))
                
                # Save model and config
                if args.save_model:
                    model_path = layer_dir / 'verbalised_confidence_probe.pkl'
                    with open(model_path, 'wb') as f:
                        pickle.dump({
                            'model': model,
                            'metrics': metrics,
                            'layer_idx': layer_idx,
                            'token_pos': token_pos,
                            'embedding_type': embedding_type,
                            'model_type': args.model_type,
                            'alpha': args.alpha if args.model_type == 'ridge' else None,
                        }, f)
                    
                    layer_args = argparse.Namespace(layer_idx=layer_idx, alpha=args.alpha)
                    write_config_txt(
                        layer_dir, layer_args, args.model_type,
                        n_train=len(X_train_l), n_val=len(X_val_l),
                        metrics=metrics,
                        train_path=str(args.train_path), val_path=str(args.val_path),
                    )
                    logging.debug(f"Saved model and config to {layer_dir}")
            
            # Generate per-token graphs
            logging.info(f"Generating per-token graphs for {token_dir_name}...")
            _plot_all_metrics_by_layer(
                token_dir,
                layer_numbers,
                [train_mse, train_mae, train_r2],
                [val_mse, val_mae, val_r2],
            )
            
            # Store metrics for cross-token graphs
            all_token_metrics[token_dir_name] = {
                'train': [train_mse, train_mae, train_r2],
                'val': [val_mse, val_mae, val_r2],
                'layers': layer_numbers,
            }
    
    # Generate cross-token graphs
    if len(all_token_metrics) > 0:
        logging.info("\nGenerating cross-token graphs...")
        _plot_metrics_all_tokens(run_base, all_token_metrics)
    
    logging.info(f"\nDone. Trained probes saved in {run_base}")


if __name__ == '__main__':
    main()
